app = "fly-io-zr3wvq"
primary_region = "sin"

[build]

[env]
  PORT = "8080"

# Không dùng http_service vì đây là TCP proxy, không phải web app
[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 8080

  # TCP check - chỉ cần check port có listen không
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
